# Generated by Django 4.2.17 on 2024-12-10 07:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_end_date_remove_booking_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
