# Generated by Django 4.2.17 on 2024-12-18 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_itinerary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
