# Generated by Django 4.2.17 on 2024-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_itinerary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
